FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps

COPY packages ./packages

#install dependencies
RUN npm install

RUN cd packages/db && npx prisma generate && cd ../..

RUN npm run build

CMD ["npm", "run", "start-user-app"]